### ISSUE TITLE
Test kullanıcısı

### ISSUE THREAD

**Issue by icobani** [ozgur-soft/garantipay#1]
Merhaba,
örnekteki terminal id için aşağıdaki sisteme girişi için lazım olan  bilgiler nelerdir. yardımcı olabilir misiniz.

işyerino 	       : 
Kullanıcı Adı   : 
Parola    	       : 
Şifre  	       : 

https://sanalposwebtest.garanti.com.tr

**Comment by 0zgurYalcin** [comment]
Bu bilgilere bankaya yaptığınız sanal pos başvurunuz onaylandıktan sonra bankanın size bildirdiği yönetici paneli üzerinden oluşturulabilmektedir. Geliştiricilere özel verilen genel bir kullanıcı tanımı bulunmamaktadır.
